import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags as t } from "@lezer/highlight";
import type { Extension } from "@codemirror/state";
import type { ColorScheme } from "../theme";

/** VS Code Dark+-inspired palette (JS / TS / Python via Lezer tags). */
const highlightDark = HighlightStyle.define([
  { tag: t.comment, color: "#6A9955" },
  { tag: t.lineComment, color: "#6A9955" },
  { tag: t.blockComment, color: "#6A9955" },
  { tag: t.docComment, color: "#6A9955" },
  { tag: t.keyword, color: "#569CD6" },
  { tag: t.controlKeyword, color: "#C586C0" },
  { tag: t.moduleKeyword, color: "#C586C0" },
  { tag: t.operatorKeyword, color: "#569CD6" },
  { tag: t.definitionKeyword, color: "#569CD6" },
  { tag: t.modifier, color: "#569CD6" },
  { tag: t.self, color: "#569CD6" },
  { tag: t.null, color: "#569CD6" },
  { tag: t.bool, color: "#569CD6" },
  { tag: t.atom, color: "#569CD6" },
  { tag: t.string, color: "#CE9178" },
  { tag: t.special(t.string), color: "#CE9178" },
  { tag: t.character, color: "#CE9178" },
  { tag: t.regexp, color: "#D16969" },
  { tag: t.escape, color: "#D7BA7D" },
  { tag: t.number, color: "#B5CEA8" },
  { tag: t.integer, color: "#B5CEA8" },
  { tag: t.float, color: "#B5CEA8" },
  { tag: t.function(t.variableName), color: "#DCDCAA" },
  { tag: t.function(t.propertyName), color: "#DCDCAA" },
  { tag: t.definition(t.function(t.variableName)), color: "#DCDCAA" },
  { tag: t.variableName, color: "#9CDCFE" },
  { tag: t.definition(t.variableName), color: "#9CDCFE" },
  { tag: t.propertyName, color: "#9CDCFE" },
  { tag: t.definition(t.propertyName), color: "#9CDCFE" },
  { tag: t.typeName, color: "#4EC9B0" },
  { tag: t.namespace, color: "#4EC9B0" },
  { tag: t.className, color: "#4EC9B0" },
  { tag: t.labelName, color: "#C8C8C8" },
  { tag: t.operator, color: "#D4D4D4" },
  { tag: t.punctuation, color: "#D4D4D4" },
  { tag: t.bracket, color: "#FFD700" },
  { tag: t.paren, color: "#D4D4D4" },
  { tag: t.squareBracket, color: "#D4D4D4" },
  { tag: t.brace, color: "#D4D4D4" },
  { tag: t.separator, color: "#D4D4D4" },
  { tag: t.angleBracket, color: "#808080" },
  { tag: t.meta, color: "#9B9B9B" },
  { tag: t.invalid, color: "#F44747" },
]);

/** VS Code Light+-inspired palette. */
const highlightLight = HighlightStyle.define([
  { tag: t.comment, color: "#008000" },
  { tag: t.lineComment, color: "#008000" },
  { tag: t.blockComment, color: "#008000" },
  { tag: t.docComment, color: "#008000" },
  { tag: t.keyword, color: "#0000FF" },
  { tag: t.controlKeyword, color: "#AF00DB" },
  { tag: t.moduleKeyword, color: "#AF00DB" },
  { tag: t.operatorKeyword, color: "#0000FF" },
  { tag: t.definitionKeyword, color: "#0000FF" },
  { tag: t.modifier, color: "#0000FF" },
  { tag: t.self, color: "#0000FF" },
  { tag: t.null, color: "#0000FF" },
  { tag: t.bool, color: "#0000FF" },
  { tag: t.atom, color: "#0000FF" },
  { tag: t.string, color: "#A31515" },
  { tag: t.special(t.string), color: "#A31515" },
  { tag: t.character, color: "#A31515" },
  { tag: t.regexp, color: "#811F3F" },
  { tag: t.escape, color: "#EE0000" },
  { tag: t.number, color: "#098658" },
  { tag: t.integer, color: "#098658" },
  { tag: t.float, color: "#098658" },
  { tag: t.function(t.variableName), color: "#795E26" },
  { tag: t.function(t.propertyName), color: "#795E26" },
  { tag: t.definition(t.function(t.variableName)), color: "#795E26" },
  { tag: t.variableName, color: "#001080" },
  { tag: t.definition(t.variableName), color: "#001080" },
  { tag: t.propertyName, color: "#001080" },
  { tag: t.definition(t.propertyName), color: "#001080" },
  { tag: t.typeName, color: "#267F99" },
  { tag: t.namespace, color: "#267F99" },
  { tag: t.className, color: "#267F99" },
  { tag: t.labelName, color: "#000000" },
  { tag: t.operator, color: "#000000" },
  { tag: t.punctuation, color: "#000000" },
  { tag: t.bracket, color: "#0431FA" },
  { tag: t.paren, color: "#000000" },
  { tag: t.squareBracket, color: "#000000" },
  { tag: t.brace, color: "#000000" },
  { tag: t.separator, color: "#000000" },
  { tag: t.angleBracket, color: "#800000" },
  { tag: t.meta, color: "#808080" },
  { tag: t.invalid, color: "#CD3131" },
]);

export function highlightExtension(scheme: ColorScheme): Extension {
  return syntaxHighlighting(
    scheme === "dark" ? highlightDark : highlightLight,
    { fallback: true },
  );
}
